refactor: refactor release workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -8,37 +8,51 @@ on:
         required: false
         type: string
         default: 'patch'
+      source-branch:
+        description: 'The source branch to release from'
+        required: false
+        type: string
+        default: 'develop'
+      target-branch:
+        description: 'The target branch to merge the release into'
+        required: false
+        type: string
+        default: 'main'
     secrets:
         GH_ACTION_PAT:
             description: 'GitHub Personal Access Token with repo permissions'
             required: true
 
+env:
+  BRANCHES_TO_PUSH: "{{ inputs.source-branch }} {{ inputs.target-branch }}"
+  SOURCE_BRANCH: ${{ inputs.source-branch }}
+  TARGET_BRANCH: ${{ inputs.target-branch }}
 jobs:
   release:
     runs-on: ubuntu-latest
     permissions:
       contents: write
     steps:
-      - name: Checkout develop branch
+      - name: Checkout source branch
         uses: actions/checkout@v4
         with:
           fetch-depth: 0  
           token: ${{ secrets.GH_ACTION_PAT }}
-          ref: develop
+          ref: ${{ inputs.source-branch }}
             
-      - name: Validate release type
-        run: |
-          if [[ "${{ inputs.type }}" != "patch" && "${{ inputs.type }}" != "minor" && "${{ inputs.type }}" != "major" ]]; then
-            echo "Invalid release type: ${{ inputs.type }}. Must be one of: patch, minor, major."
-            exit 1
-          fi
+      # - name: Validate release type
+      #   run: |
+      #     if [[ "${{ inputs.type }}" != "patch" && "${{ inputs.type }}" != "minor" && "${{ inputs.type }}" != "major" ]]; then
+      #       echo "Invalid release type: ${{ inputs.type }}. Must be one of: patch, minor, major."
+      #       exit 1
+      #     fi
 
-      - name: Ensure branch is develop
-        run: |
-          if [[ "${GITHUB_REF##*/}" != "develop" ]]; then
-            echo "This workflow can only be run from the develop branch."
-            exit 1
-          fi
+      # - name: Ensure branch is source branch
+      #   run: |
+      #     if [[ "${GITHUB_REF##*/}" != "${{ inputs.source-branch }}" ]]; then
+      #       echo "This workflow can only be run from the ${{ inputs.source-branch }} branch."
+      #       exit 1
+      #     fi
 
       - name: Set git user
         run: |
@@ -57,7 +71,12 @@ jobs:
         with:
           current-version: ${{ steps.get_version.outputs.current_version }}
           release-type: ${{ inputs.type }}
-           
+      
+      - name: Check out to target branch and merge source branch
+        run: |
+          git fetch --all
+          git checkout "${TARGET_BRANCH}"
+          git merge -v "${SOURCE_BRANCH}"
 
       - name: Bump version (release)
         id: version
@@ -65,22 +84,18 @@ jobs:
           NEXT_VERSION: ${{ steps.next_version.outputs.release-version }}
         run: |
           RELEASE_VERSION=$(npm version $NEXT_VERSION --no-git-tag-version)
-          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
+          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT        
 
-      - name: Commit and push release version to develop
+      - name: Commit release version to target branch
         env:
           RELEASE_VERSION: ${{ steps.version.outputs.release_version }}
         run: |
           git add package.json package-lock.json || true
           git commit -m "chore(release): $RELEASE_VERSION"
-          git push origin develop
 
-      - name: Merge release to main
+      - name: Create Changelog
         run: |
-          git fetch origin main
-          git checkout main
-          git merge -v origin/develop
-          git push origin main
+          echo "Generating changelog..."
 
       - name: Tag and create GitHub Release
         uses: softprops/action-gh-release@v1
@@ -90,6 +105,11 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
+      - name: Switch back to source branch and merge target branch
+        run: |
+          git checkout "${SOURCE_BRANCH}"
+          git merge -v "${TARGET_BRANCH}"
+      
       - name: Get snapshot version
         id: snapshot_version
         uses: mchtugr/get-release-version@v1
@@ -98,12 +118,14 @@ jobs:
           release-type: patch
           generate-snapshot: true
 
-      - name: Switch back to develop and set snapshot version
+      - name: Switch back to source branch and set snapshot version
         env: 
           SNAPSHOT_VERSION: ${{ steps.snapshot_version.outputs.release-version }}
         run: |
-          git checkout develop
+          git checkout ${{ inputs.source-branch }}
           npm version $SNAPSHOT_VERSION --no-git-tag-version
           git add package.json package-lock.json || true
           git commit -m "chore(release-candidate): v$SNAPSHOT_VERSION"
-          git push origin develop
+      - name: Push changes to remote branches
+        run: |
+          git push --atomic ${{ env.BRANCHES_TO_PUSH }}
